cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --job-name=local-haplo-benchmark-{rule}-{wildcards}
    --cpus-per-task={threads}
    --mem-per-cpu="$(( {resources.mem_mb} / {threads} ))"
    --time="{resources.runtime}"
    --tmp={resources.disk_mb}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out.log
    --error=logs/{rule}/{rule}-{wildcards}-%j.err.log
default-resources:
        # - partition=<name-of-default-partition>
        # - qos=<name-of-quality-of-service>
  - mem_mb=2000
  - runtime=15
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
