---
name: HIV

general:
    aligner: "ngshmmalign"

input:
    reference: "{VPIPE_BASEDIR}/../resources/hiv/HXB2.fasta"
    metainfo_file: "{VPIPE_BASEDIR}/../resources/hiv/metainfo.yaml"
    gff_directory: "{VPIPE_BASEDIR}/../resources/hiv/gffs/"
    genes_gff: "{VPIPE_BASEDIR}/../resources/hiv/gffs/GCF_000864765.1_ViralProj15476_genomic.gff"

bwa_QA:
    ref_panel: "{VPIPE_BASEDIR}/../resources/hiv/5-Virus-Mix.fasta"
