method_list: [lofreq_local_haplo,
              shorah_default,
              predicthaplo_local_haplo,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_tf0.1,
              cliquesnv_local_haplo_tf0.01,
              viloca_alpha_0.00001,
              #strainline,  failed in clustering step
              # shorah_default_amplicon, --> here the short illumina simulation still not work due to b2w errors
              ]
replicate_count: 5
haplotype_generation: distance
params_path: config_distance/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
